/*
 * Library
 *
 * Demo Library API
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	sw "github.com/khalilgalalem/library/go"
)

func main() {
	log.Printf("Server started")

	router := sw.NewRouter()

	// Initialize metrics and wrap the router
	http.Handle("/", sw.MetricsMiddleware(router))

	// Expose the metrics endpoint at /metrics
	http.Handle("/metrics", sw.PromHandler())

	log.Fatal(http.ListenAndServe(":8080", nil))
}
