/*
 * Library
 *
 * Demo Library API
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A book example
type Book struct {

	ID int32 `json:"id,omitempty"`

	Title string `json:"title,omitempty"`

	Description string `json:"description,omitempty"`

	Author string `json:"author,omitempty"`
}
